name: "damas"

on:
  issues:
    types: [opened]

jobs:
  move:
    runs-on: ubuntu-latest
    if: startsWith(github.event.issue.title, 'damas-')
    steps:
      - if: startsWith(github.event.issue.title, 'damas-') && contains(github.event.issue.labels.*.name, 'test')
        run: |
          # the triggering issue contains test
          echo "${{ github.event_name }}"
          exit 1